name: doublepick
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+102

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.0
  sign_in_with_apple: ^6.0.0
  firebase_core: ^4.15.0
  firebase_auth: ^6.7.0
  cloud_firestore: ^6.10.0
  firebase_storage: ^13.6.0
  firebase_messaging: ^16.7.0
  google_mobile_ads: ^9.1.0
  connectivity_plus: ^7.3.1
  permission_handler: ^13.0.2
  screenshot: ^3.0.0
  flutter_local_notifications: ^22.3.1
  image_picker: ^1.2.3
  device_info_plus: ^13.2.0
  share_plus: ^13.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.7   # koristi verziju koja radi sa tvojim SDK-om
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_firme.png
    - assets/images/lodoapp.png
    - assets/images/slika1.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/lodoapp.png"
  adaptive_icon_background: "#90EE90"
  adaptive_icon_foreground: "assets/images/lodoapp.png"

flutter_native_splash:
  android: true
  ios: true
  color: "#008000"                # zelena pozadina
  image: "assets/images/slika1.png"

